#apiVersion: secretgen.carvel.dev/v1alpha1
#kind: SecretExport
#metadata:
#  name: postgres-gpu
#  namespace: default
#spec:
#  toNamespaces:
#    - YOUR_SECRET_TARGET_NAMESPACE
#---
#apiVersion: secretgen.carvel.dev/v1alpha1
#kind: SecretImport
#metadata:
#  name: YOUR_SECRET_NAME
#  namespace: YOUR_SECRET_TARGET_NAMESPACE
#  labels:
#    backstage-dashboard-category: YOUR_TOOL_CATEGORY
#    backstage-dashboard-name: YOUR_SERVICE_NAME
#    backstage-dashboard-type: service
#spec:
#  fromNamespace: YOUR_SECRET_SOURCE_NAMESPACE
---
#apiVersion: v1
#data:
#  database: cG9zdGdyZXM=
#  host: MzQuMjA3LjExMC4xNDM=
#  password: Vm13YXJlMQ==
#  port: NTQzMg==
#  provider: dm13YXJl
#  type: cG9zdGdyZXM=
#  username: cGdhZG1pbg==
#kind: Secret
#metadata:
#  labels:
#    backstage-dashboard-category: postgres
#    backstage-dashboard-name: pg-gpu
#    backstage-dashboard-type: service
#  name: pg-gpu
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: bkstg-default-pg-gpu
spec:
  description:
    short: Demo Postgres GPU instance
  pool:
    kind: secret
    labelSelector:
      matchLabels:
        backstage-dashboard-name: pg-gpu
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  labels:
    backstage-dashboard-category: postgres
    backstage-dashboard-name: pg-gpu
    backstage-dashboard-type: binding
  name: bkstg-default-pg-gpu
spec:
  classRef:
    name: bkstg-default-pg-gpu
