properties:
    vmware-postgres:
        service_group: "sql.tanzu.vmware.com"
        service_apigroup: "postgres.sql.tanzu.vmware.com"
        service_kind: "Postgres"
        service_category: "postgres"
        service_additional_label: ""
        service_cluster_instance_class: ""
        service_link: ""
        service_linkname: ""
        service_linkdescription: ""
    bitnami-postgres:
        service_group: ""
        service_apigroup: "statefulset"
        service_kind: "StatefulSet"
        service_category: "postgres"
        service_additional_label: "app.kubernetes.io/name=postgresql,app.kubernetes.io/managed-by=Helm"
        service_cluster_instance_class: "postgresql-unmanaged"
        service_link: ""
        service_linkname: ""
        service_linkdescription: ""
    bitnami-mongodb:
        service_group: ""
        service_apigroup: "deployment"
        service_kind: "Deployment"
        service_category: "mongodb"
        service_additional_label: "app.kubernetes.io/name=mongodb,app.kubernetes.io/managed-by=Helm"
        service_cluster_instance_class: "mongodb-unmanaged"
        service_link: ""
        service_linkname: ""
        service_linkdescription: ""
    bitnami-redis:
        service_group: ""
        service_apigroup: "statefulset"
        service_kind: "StatefulSet"
        service_category: "redis"
        service_additional_label: "app.kubernetes.io/name=redis,app.kubernetes.io/managed-by=Helm"
        service_cluster_instance_class: "redis-unmanaged"
        service_link: ""
        service_linkname: ""
        service_linkdescription: ""
    greenplum:
        service_group: ""
        service_apigroup: "secret"
        service_kind: "Secret"
        service_category: "greenplum"
        service_additional_label: ""
        service_cluster_instance_class: ""
        service_link: "http://ec2-44-201-91-88.compute-1.amazonaws.com:28080"
        service_linkname: "greenplum-training"
        service_linkdescription: "AWS Marketplace Training Instance"
    mlflow:
        service_group: ""
        service_apigroup: ""
        service_kind: ""
        service_category: "mlflow"
        service_additional_label: ""
        service_cluster_instance_class: ""
        service_link: "http://mlflow.tanzudatatap.com"
        service_linkname: "mlflow-main"
        service_linkdescription: "Dev Instance"
    datahub:
        service_group: ""
        service_apigroup: ""
        service_kind: ""
        service_category: "datahub"
        service_additional_label: ""
        service_cluster_instance_class: ""
        service_link: "http://datahub-datahub.tanzudatatap.com"
        service_linkname: "datahub-main"
        service_linkdescription: "Main Data Catalog"
    scdf:
        service_group: ""
        service_apigroup: ""
        service_kind: ""
        service_category: "scdf"
        service_additional_label: ""
        service_cluster_instance_class: ""
        service_link: "http://scdf.tanzudatatap.com/dashboard"
        service_linkname: "scdf-main"
        service_linkdescription: "Pre-prod instance"
    gemfire:
        service_group: ""
        service_apigroup: ""
        service_kind: ""
        service_category: "gemfire"
        service_additional_label: ""
        service_cluster_instance_class: ""
        service_link: "http://gfanomaly-locator.tanzudatatap.com/pulse"
        service_linkname: "gemfire-main"
        service_linkdescription: "Dev Feature Store"
    kubeflow-pipelines:
        service_group: ""
        service_apigroup: ""
        service_kind: ""
        service_category: "kubeflowpipelines"
        service_additional_label: ""
        service_cluster_instance_class: ""
        service_link: "http://kubeflow-pipelines.tanzudatatap.com/#/pipelines"
        service_linkname: "kubeflow-pipelines-main"
        service_linkdescription: "Dev Training Environment"
    jupyter:
        service_group: ""
        service_apigroup: ""
        service_kind: ""
        service_category: "jupyter"
        service_additional_label: ""
        service_cluster_instance_class: ""
        service_link: "http://jupyter-jupyterhub.tanzudatatap.com"
        service_linkname: "jupyter-main"
        service_linkdescription: "Main Hub"
    argo:
        service_group: ""
        service_apigroup: ""
        service_kind: ""
        service_category: "argo"
        service_additional_label: ""
        service_cluster_instance_class: ""
        service_link: "https://argo-workflows.tanzudatatap.com/"
        service_linkname: "argoworkflows-main"
        service_linkdescription: "Dev Pipelines"
    huggingface:
        service_group: ""
        service_apigroup: ""
        service_kind: ""
        service_category: "huggingface"
        service_additional_label: ""
        service_cluster_instance_class: ""
        service_link: "https://huggingface.co/tanzuhuggingface"
        service_linkname: "huggingface-main"
        service_linkdescription: "Tanzu Hub"
    evidently:
        service_group: ""
        service_apigroup: ""
        service_kind: ""
        service_category: "evidently"
        service_additional_label: ""
        service_cluster_instance_class: ""
        service_link: "https://evidently-ui.default.tanzumlai.com/"
        service_linkname: "evidently-main"
        service_linkdescription: "Dev Monitoring Instance"