configMapGenerator:
  - name: ml-backstage-configmap
    files:
      - automation-fields.yaml
      - task.sh
  - name: env-configmap
    files:
      - image_repo
      - backstage_namespace
resources:
  - automation-job.yaml
replacements:
  - source:
      kind: ConfigMap
      name: env-configmap
      fieldPath: data.image_repo
    targets:
      - select:
          kind: CronJob
          name: ml-backstage-job
        fieldPaths:
          - spec.jobTemplate.spec.template.spec.containers.[name=load-params].image
  - source:
      kind: ConfigMap
      name: env-configmap
      fieldPath: data.backstage_namespace
    targets:
      - select:
          kind: CronJob
          name: ml-backstage-job
        fieldPaths:
          - spec.jobTemplate.spec.template.spec.containers.[name=load-params].env.[name=ML_BACKSTAGE_TARGET_NAMESPACE].value
