vmware-postgres:
    service_group: "sql.tanzu.vmware.com"
    service_apigroup: "postgres.sql.tanzu.vmware.com"
    service_kind: "Postgres"
    service_category: "postgres"
    service_additional_label: ""
    service_cluster_instance_class: ""
    service_link: ""
    service_linkname: ""
bitnami-postgres:
    service_group: ""
    service_apigroup: "statefulset"
    service_kind: "StatefulSet"
    service_category: "postgres"
    service_additional_label: "app.kubernetes.io/name=postgresql,app.kubernetes.io/managed-by=Helm"
    service_cluster_instance_class: "postgresql-unmanaged"
    service_link: ""
    service_linkname: ""
greenplum:
    service_group: ""
    service_apigroup: "secret"
    service_kind: "Secret"
    service_category: "greenplum"
    service_additional_label: ""
    service_cluster_instance_class: ""
    service_link: "ec2-44-201-91-88.compute-1.amazonaws.com:28080"
    service_linkname: "greenplum-training"
mlflow:
    service_group: ""
    service_apigroup: ""
    service_kind: ""
    service_category: "mlflow"
    service_additional_label: ""
    service_cluster_instance_class: ""
    service_link: "http://mlflow.tanzudatatap.com"
    service_linkname: "mlflow-main"
datahub:
    service_group: ""
    service_apigroup: ""
    service_kind: ""
    service_category: "datahub"
    service_additional_label: ""
    service_cluster_instance_class: ""
    service_link: "http://datahub-datahub.tanzudatatap.com"
    service_linkname: "datahub-main"
scdf:
    service_group: ""
    service_apigroup: ""
    service_kind: ""
    service_category: "scdf"
    service_additional_label: ""
    service_cluster_instance_class: ""
    service_link: "http://scdf.tanzudatatap.com/dashboard"
    service_linkname: "scdf-main"