#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: #@ data.values.secret_name
  namespace: #@ data.values.secret_source_namespace
spec:
  toNamespaces:
    - #@ data.values.secret_target_namespace
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: #@ data.values.secret_name
  namespace: #@ data.values.secret_target_namespace
  labels:
    backstage-dashboard-category: #@ data.values.tool_category
    backstage-dashboard-name: #@ data.values.service_name
    backstage-dashboard-type: service
spec:
  fromNamespace: #@ data.values.secret_source_namespace