#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
data:
  database: #@ base64.encode(data.values.binding_database)
  host: #@ base64.encode(data.values.binding_host)
  password: #@ base64.encode(data.values.binding_password)
  port: #@ base64.encode(data.values.binding_port)
  provider: #@ base64.encode(data.values.binding_provider)
  type: #@ base64.encode(data.values.binding_type)
  username: #@ base64.encode(data.values.binding_username)
  schema: #@ base64.encode(data.values.binding_schema)
  url: #@ base64.encode(data.values.binding_url)
kind: Secret
metadata:
  labels:
    backstage-dashboard-category: #@ data.values.tool_category
    backstage-dashboard-name: #@ data.values.service_name
    backstage-dashboard-type: service
    instance_type: tanzu_vm
  name: #@ data.values.secret_name
  namespace: #@ data.values.secret_target_namespace