apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: YOUR_SECRET_NAME
  namespace: YOUR_SECRET_SOURCE_NAMESPACE
spec:
  toNamespaces:
    - YOUR_SECRET_TARGET_NAMESPACE
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: YOUR_SECRET_NAME
  namespace: YOUR_SECRET_TARGET_NAMESPACE
  labels:
    backstage-dashboard-category: YOUR_TOOL_CATEGORY
    backstage-dashboard-name: YOUR_SERVICE_NAME
    backstage-dashboard-type: service
spec:
  fromNamespace: YOUR_SECRET_SOURCE_NAMESPACE
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: bkstg-YOUR_TOOL_CATEGORY-YOUR_SERVICE_NAME
spec:
  description:
    short: YOUR_CLUSTER_CLASS_DESCRIPTION
  pool:
    kind: secret
    labelSelector:
      matchLabels:
        backstage-dashboard-name: YOUR_SERVICE_NAME
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  labels:
    backstage-dashboard-category: YOUR_TOOL_CATEGORY
    backstage-dashboard-name: YOUR_SERVICE_NAME
    backstage-dashboard-type: binding
  name: bkstg-YOUR_TOOL_CATEGORY-YOUR_SERVICE_NAME
spec:
  classRef:
    name: bkstg-YOUR_TOOL_CATEGORY-YOUR_SERVICE_NAME
