apiVersion: v1
kind: ServiceAccount
metadata:
  name: bkstg-automation
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bkstg-automation
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["services.apps.tanzu.vmware.com/v1alpha1"]
    resources: ["classclaims"]
    verbs: ["*"]
  - apiGroups: ["services.apps.tanzu.vmware.com/v1alpha1"]
    resources: ["resourceclaims"]
    verbs: ["*"]
  - apiGroups: ["servicebinding.io/v1beta1"]
    resources: ["servicebindings"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bkstg-automation
subjects:
  - kind: ServiceAccount
    name: bkstg-automation
    namespace: default
roleRef:
  kind: ClusterRole
  name: bkstg-automation
  apiGroup: rbac.authorization.k8s.io
