apiVersion: batch/v1
kind: CronJob
metadata:
  name: ml-backstage-job
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: tap-gui
          containers:
            - name: load-params
              image: $(image_repo)
              env:
                - name: ML_BACKSTAGE_TARGET_NAMESPACE
                  value: $(backstage_namespace)
              volumeMounts:
                - name: ml-backstage-configmap-volume
                  mountPath: /usr/src/app
              command:
                - sh
                - "-c"
                - |
                  export ML_PROPERTIES_FILE=/usr/src/app/data.yaml
                  /usr/src/app/task.sh
          restartPolicy: Never
          volumes:
            - name: ml-backstage-configmap-volume
              configMap:
                name: ml-backstage-configmap
                defaultMode: 0777