configMapGenerator:
  - name: ml-backstage-configmap
    files:
      - data.yaml
      - task.sh
      - task-debug.sh
  - name: env-configmap
    files:
      - image_repo
resources:
  - job.yaml
replacements:
  - source:
      kind: ConfigMap
      name: env-configmap
      fieldPath: data.image_repo
    targets:
      - select:
          kind: CronJob
          name: ml-backstage-job
        fieldPaths:
          - spec.jobTemplate.spec.template.spec.containers.[name=load-params].image
